accelerator: null
accumulate_grad_batches: null
amp_backend: native
amp_level: null
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 64
benchmark: false
check_val_every_n_epoch: 1
checkpoint_callback: null
concat: true
data: losloop
default_root_dir: null
detect_anomaly: false
deterministic: false
devices: null
dropout: 0.0
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
fast_dev_run: false
feat_max_val: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - f4
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AACMQg==
flush_logs_every_n_steps: null
gpus:
- 0
gradient_clip_algorithm: null
gradient_clip_val: 0
heads: 2
hid_channels: 100
ipus: null
learning_rate: 0.001
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 50
log_gpu_memory: null
log_name: logs_losloop
log_path: lightning_logs
logger: !!python/object:pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  _agg_default_func: !!python/name:numpy.mean ''
  _agg_key_funcs: {}
  _default_hp_metric: true
  _experiment: null
  _fs: !!python/object/apply:fsspec.spec.make_instance
  - !!python/name:fsspec.implementations.local.LocalFileSystem ''
  - !!python/tuple []
  - {}
  _kwargs: {}
  _log_graph: false
  _metrics_to_agg: []
  _name: ''
  _prefix: ''
  _prev_step: -1
  _save_dir: lightning_logs
  _sub_dir: null
  _version: null
  hparams: {}
loss: mse_with_regularizer
max_epochs: 3
max_steps: -1
max_time: null
min_epochs: null
min_steps: null
model_name: GAT
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
normalize: true
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
overfit_batches: 0.0
plugins: null
pre_len: 6
precision: 32
prepare_data_per_node: null
process_position: 0
profiler: null
progress_bar_refresh_rate: null
reload_dataloaders_every_epoch: false
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
result_path: results
resume_from_checkpoint: null
seq_len: 12
share_weights: false
stochastic_weight_avg: false
strategy: null
sync_batchnorm: false
terminate_on_nan: null
test_size: 0.15
tpu_cores: null
track_grad_norm: -1
val_check_interval: 1.0
val_size: 0.15
weight_decay: 0.0
weights_save_path: null
weights_summary: top
